name: dbt compile

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  compile:
    runs-on: ubuntu-latest
    env:
      DBT_PROFILES_DIR: ${{ runner.temp }}/dbt-profiles
      GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/bq-key.json

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: pip install uv

      - name: Sync dependencies
        run: uv sync --dev

      - name: Prepare dbt profile and credentials
        run: |
          mkdir -p "$DBT_PROFILES_DIR"
          cat <<'PROFILE' > "$DBT_PROFILES_DIR/profiles.yml"
          dbt_buckets:
            target: ci
            outputs:
              ci:
                type: bigquery
                method: service-account
                keyfile: "$GOOGLE_APPLICATION_CREDENTIALS"
                project: bigquery-sandbox-cpvuft6h
                dataset: dbt_unit_tests
                location: EU
                threads: 1
          PROFILE
          echo '${{ secrets.BQ_SERVICE_ACCOUNT_JSON }}' > "$GOOGLE_APPLICATION_CREDENTIALS"

      - name: dbt deps
        run: uv run python -m dbt.cli.main deps

      - name: dbt compile
        run: uv run python -m dbt.cli.main compile
