name: dbt compile

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: pip install uv

      - name: Sync dependencies
        run: uv sync --extra dev

      - name: Configure dbt environment variables
        run: |
          echo "DBT_PROFILES_DIR=$RUNNER_TEMP/dbt-profiles" >> "$GITHUB_ENV"
          echo "GOOGLE_APPLICATION_CREDENTIALS=$RUNNER_TEMP/bq-key.json" >> "$GITHUB_ENV"

      - name: Prepare dbt profile and credentials
        env:
          BQ_SERVICE_ACCOUNT_JSON_BASE64: ${{ secrets.BQ_SERVICE_ACCOUNT_JSON_BASE64 }}
        run: |
          set -euo pipefail

          mkdir -p "$DBT_PROFILES_DIR"
          mkdir -p "$(dirname "$GOOGLE_APPLICATION_CREDENTIALS")"

          cat <<PROFILE > "$DBT_PROFILES_DIR/profiles.yml"
          dbt_buckets:
            target: ci
            outputs:
              ci:
                type: bigquery
                method: service-account
                keyfile: "$GOOGLE_APPLICATION_CREDENTIALS"
                project: bigquery-sandbox-cpvuft6h
                dataset: dbt_unit_tests
                location: EU
                threads: 1
          PROFILE
          if [ -z "${BQ_SERVICE_ACCOUNT_JSON_BASE64:-}" ]; then
            echo "BQ_SERVICE_ACCOUNT_JSON_BASE64 secret is empty" >&2
            exit 1
          fi

          echo "Loaded service account key (base64) length: ${#BQ_SERVICE_ACCOUNT_JSON_BASE64}"
          printf '%s' "$BQ_SERVICE_ACCOUNT_JSON_BASE64" | base64 --decode > "$GOOGLE_APPLICATION_CREDENTIALS"
          echo "Rendered dbt profile (for debugging):"
          cat "$DBT_PROFILES_DIR/profiles.yml"
          echo "Service account key bytes: $(wc -c < "$GOOGLE_APPLICATION_CREDENTIALS")"

      - name: dbt deps
        run: uv run --extra dev python -m dbt.cli.main deps

      - name: dbt compile
        run: uv run --extra dev python -m dbt.cli.main compile
