name: dbt compile

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  compile:
    runs-on: ubuntu-latest
    env:
      DBT_PROFILES_DIR: .github/dbt

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: pip install uv

      - name: Sync dependencies
        run: uv sync --dev

      - name: Prepare dbt profile
        run: |
          mkdir -p $DBT_PROFILES_DIR
          cat <<'PROFILE' > $DBT_PROFILES_DIR/profiles.yml
          dbt_buckets:
            target: ci
            outputs:
              ci:
                type: bigquery
                method: service-account
                keyfile: /tmp/fake-service-account.json
                project: bigquery-sandbox-cpvuft6h
                dataset: dbt_unit_tests
                location: EU
                threads: 1
          PROFILE
          echo '{}' > /tmp/fake-service-account.json

      - name: dbt deps
        run: uv run dbt deps

      - name: dbt compile
        run: uv run dbt compile
